# Configuration file for the Spawn Plugin

# If set to 'true', players will not take fall damage after using the spawn command.
# If set to 'false', fall damage will apply as usual.
prevent-fall-damage-on-command: false

# The cooldown time (in seconds) before a player can use the spawn command again.
# Set to '0' for no cooldown (players can use the command instantly).
cooldown: 0
