name: tpspawn
version: '1.0.2'
main: me.honeyberries.tpspawn.TPSpawn
api-version: '1.19'
authors: [ HoneyBerries ]
description: Lets you go to the world spawn by using /spawn
commands:
  spawn:
    description: "Lets you go to spawn instantly with /spawn"
    usage: "/spawn"
    aliases: []

  tpspawn:
    description: "Lets you modify the plugin settings"
    usage: "/tpspawn <action> <value>"
    aliases: []

permissions:
  tpspawn.command.spawn:
    description: "Allows a player to use /spawn"
    default: true
  tpspawn.cooldown.bypass:
    description: "Allows you to bypass the cooldown"
    default: op
  tpspawn.command.edit:
    description: "Lets you reload config and edit stuff"
    default: op
